### ISSUE TITLE
freedb connection refused

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bleskodev/rubyripper#567]
```
1) Please describe the steps to reproduce the situation:
a. Launch rrip_gui from an Ubuntu 12.04 console,
b. Configure freedb server: http://freedb.musicbrainz.org:80/~cddb/cddb.cgi
c. Scan drive loaded with music CD

2) What is the expected output? What do you see instead?
CD album and track data should be populated, instead the GUI reports it can't 
find the freedb server and the console shows the following error message:
Scanning disc with cdrdao
cddb query 1 = 
/~cddb/cddb.cgi?cmd=cddb+query+db0b700f+15+150+2180+21350+40727+44417+61775+8163
2+100212+110150+122920+141555+161890+165845+184222+200740+2930&hello=my_email%40
gmail.com+my_secret.com+rubyripper+0.6.2&proto=6
Exception thrown: Connection refused - connect(2)

MusicBrainz Picard is able to load the CD info.

3) What version of rubyripper are you using? On what operating system? The
gtk2 of commandline interface?
Using rubyripper 0.6.2 gtk2 UI on Ubuntu 12.04 with ruby upgraded to v1.9.1.

4) Is this not already fixed with the latest & greatest code? See for
instructions the Source tab above.
Yes, v0.7.0a1 fetched from git today works correctly.

5) Does the problem happen with all discs? If not, please attach
the output of cdparanoia -Q with a disc that gives trouble.
Yes

6) Please explain why this change is important for you. Also, how many
users would benefit from this change?
The stable version available for download may be non-functional with freedb.

Please provide any additional information below. The more usefull
information provided, the sooner the issue will be fixed.

There appear to be some potential Ruby issues.

rrip_gui from 0.6.2
-------------------
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be 
deprecated in the future, use String#encode instead.
/usr/lib/ruby/1.9.1/gettext/runtime/locale_path.rb:20: Use RbConfig instead of 
obsolete and deprecated Config.
NOTE: Gem.all_load_paths is deprecated with no replacement. It will be removed 
on or after 2011-10-01.
Gem.all_load_paths called from 
/usr/lib/ruby/1.9.1/gettext/runtime/locale_path.rb:56.
NOTE: Gem.all_partials is deprecated with no replacement. It will be removed on 
or after 2011-10-01.
Gem.all_partials called from /usr/lib/ruby/1.9.1/rubygems.rb:258.
NOTE: Gem.all_partials is deprecated with no replacement. It will be removed on 
or after 2011-10-01.
Gem.all_partials called from /usr/lib/ruby/1.9.1/rubygems.rb:258.
Scanning disc with cdrdao

rubyripper_gtk2 from 0.7.0a1
----------------------------
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be 
deprecated in the future, use String#encode instead.
/usr/lib/ruby/1.9.1/gettext/runtime/locale_path.rb:20: Use RbConfig instead of 
obsolete and deprecated Config.


Note that ruby versions older than 1.9 are no longer supported. You are
advised to upgrade instead.

```

Original issue reported on code.google.com by `publicpa...@gmail.com` on 5 May 2013 at 2:55

**Comment by bleskodev** [comment]
Should be fixed in the latest code.
