### ISSUE TITLE
MusicBrainz data crash

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bleskodev/rubyripper#569]
```
1) Please describe the steps to reproduce the situation:
a. Attempt to rip new, [no label] CD (Gio - Blue Marble Lounge) added to 
MusicBrainz DB May 27, 2013.

2) What is the expected output?  The rrip GUI should display the track 
information after polling the CD.

What do you see instead?  The GUI starts, then crashes.  MusicBrainz Picard 
successfully fetches the track data.

3) What version of rubyripper are you using?  0.7.0a1
On what operating system? 64-bit Ubuntu 12.04 with Ruby 1.9.1.
The gtk2 of commandline interface? gtk2

4) Is this not already fixed with the latest & greatest code? See for
instructions the Source tab above.  Using latest git pull as of May 28 19:33 
BST.

5) Does the problem happen with all discs? NO If not, please attach
the output of cdparanoia -Q with a disc that gives trouble.

cdparanoia III release 10.2 (September 11, 2008)


Table of contents (audio tracks only):
track        length               begin        copy pre ch
===========================================================
  1.    28306 [06:17.31]        0 [00:00.00]    OK   no  2
  2.    25537 [05:40.37]    28306 [06:17.31]    OK   no  2
  3.    29581 [06:34.31]    53843 [11:57.68]    OK   no  2
  4.    24503 [05:26.53]    83424 [18:32.24]    OK   no  2
  5.    19952 [04:26.02]   107927 [23:59.02]    OK   no  2
  6.    26433 [05:52.33]   127879 [28:25.04]    OK   no  2
  7.    26724 [05:56.24]   154312 [34:17.37]    OK   no  2
  8.    19643 [04:21.68]   181036 [40:13.61]    OK   no  2
  9.    23201 [05:09.26]   200679 [44:35.54]    OK   no  2
 10.    17261 [03:50.11]   223880 [49:45.05]    OK   no  2
 11.    29683 [06:35.58]   241141 [53:35.16]    OK   no  2
TOTAL  270824 [60:10.74]    (audio only)

6) Please explain why this change is important for you. Also, how many
users would benefit from this change?  Appears to be a corner case in the 
MusicBrainz data parsing.

Please provide any additional information below. The more usefull
information provided, the sooner the issue will be fixed.

bin/rubyripper_gtk2 
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': iconv will be 
deprecated in the future, use String#encode instead.
/usr/lib/ruby/1.9.1/gettext/runtime/locale_path.rb:20: Use RbConfig instead of 
obsolete and deprecated Config.
NOTE: Gem.all_load_paths is deprecated with no replacement. It will be removed 
on or after 2011-10-01.
Gem.all_load_paths called from 
/usr/lib/ruby/1.9.1/gettext/runtime/locale_path.rb:56.
NOTE: Gem.all_partials is deprecated with no replacement. It will be removed on 
or after 2011-10-01.
Gem.all_partials called from /usr/lib/ruby/1.9.1/rubygems.rb:258.
NOTE: Gem.all_partials is deprecated with no replacement. It will be removed on 
or after 2011-10-01.
Gem.all_partials called from /usr/lib/ruby/1.9.1/rubygems.rb:258.
WARNING: Preference with key flacsettings= does not exist
WARNING: Preference with key vorbissettings= does not exist
WARNING: Preference with key mp3settings= does not exist
WARNING: Preference with key othersettings= does not exist
WARNING: Preference with key max_tries= does not exist
WARNING: Preference with key naming_normal= does not exist
WARNING: Preference with key naming_various= does not exist
WARNING: Preference with key naming_image= does not exist
WARNING: Preference with key req_matches_errors= does not exist
WARNING: Preference with key req_matches_all= does not exist
WARNING: Preference with key first_hit= does not exist
WARNING: Preference with key freedb= does not exist
WARNING: Preference with key no_log= does not exist
WARNING: Preference with key create_cue= does not exist
WARNING: Preference with key normalize= does not exist
WARNING: Preference with key gainTagsOnly= does not exist
WARNING: Preference with key pregaps= does not exist
WARNING: Preference with key freedbCache= does not exist
DEBUG: cdparanoia -d /dev/sr0 -vQ
DEBUG: cd-discid /dev/sr0
DEBUG: CGI query: 
http://freedb.musicbrainz.org/~cddb/cddb.cgi?cmd=cddb+query+9f0e1a0b+11+150+2845
6+53993+83574+108077+128029+154462+181186+200829+224030+241291+3612&hello=my_gma
il.com+my_secret.com+rubyripper+0.7.0a1&proto=6
DEBUG: CGI query: 
http://musicbrainz.org/ws/2/discid/miSVIb.HYkifAX4ncjAbHsfWP24-?toc=1+11+270974+
150+28456+53993+83574+108077+128029+154462+181186+200829+224030+241291&inc=artis
ts+recordings+artist-credits+release-groups
DEBUG: MusicBrainz status after the disc query: ok
DEBUG: CGI query: 
http://musicbrainz.org/ws/2/release-group/490102f5-1186-4160-8871-99370a96f855?i
nc=tags
DEBUG: CGI query: 
http://musicbrainz.org/ws/2/artist/c7b47234-f29a-475d-8449-f76284a889ab?inc=tags
/home/curts/incoming/rrip_git/rubyripper/lib/rubyripper/metadata/musicbrainz/mus
icbrainzReleaseParser.rb:154:in `block (2 levels) in analyzeResult': undefined 
method `<<' for nil:NilClass (NoMethodError)
    from /usr/lib/ruby/1.9.1/rexml/xpath.rb:67:in `each'
    from /usr/lib/ruby/1.9.1/rexml/xpath.rb:67:in `each'
    from /home/curts/incoming/rrip_git/rubyripper/lib/rubyripper/metadata/musicbrainz/musicbrainzReleaseParser.rb:152:in `block in analyzeResult'
    from /usr/lib/ruby/1.9.1/rexml/xpath.rb:67:in `each'
    from /usr/lib/ruby/1.9.1/rexml/xpath.rb:67:in `each'
    from /home/curts/incoming/rrip_git/rubyripper/lib/rubyripper/metadata/musicbrainz/musicbrainzReleaseParser.rb:148:in `analyzeResult'
    from /home/curts/incoming/rrip_git/rubyripper/lib/rubyripper/metadata/musicbrainz/musicbrainzReleaseParser.rb:44:in `parse'
    from /home/curts/incoming/rrip_git/rubyripper/lib/rubyripper/metadata/musicbrainz.rb:45:in `get'
    from /home/curts/incoming/rrip_git/rubyripper/lib/rubyripper/metadata/main.rb:63:in `musicbrainz'
    from /home/curts/incoming/rrip_git/rubyripper/lib/rubyripper/metadata/main.rb:54:in `startup'
    from /home/curts/incoming/rrip_git/rubyripper/lib/rubyripper/metadata/main.rb:36:in `block in get'
    from /home/curts/incoming/rrip_git/rubyripper/lib/rubyripper/metadata/main.rb:35:in `each'
    from /home/curts/incoming/rrip_git/rubyripper/lib/rubyripper/metadata/main.rb:35:in `get'
    from /home/curts/incoming/rrip_git/rubyripper/lib/rubyripper/disc/disc.rb:102:in `setMetadata'
    from /home/curts/incoming/rrip_git/rubyripper/lib/rubyripper/disc/disc.rb:40:in `scan'
    from /home/curts/incoming/rrip_git/rubyripper/lib/rubyripper/gtk2/gtkDisc.rb:44:in `refresh'
    from /home/curts/incoming/rrip_git/rubyripper/lib/rubyripper/gtk2/gtkDisc.rb:37:in `start'
    from bin/rubyripper_gtk2:146:in `block in scanDisc'


Note that ruby versions older than 1.9 are no longer supported. You are
advised to upgrade instead.

```

Original issue reported on code.google.com by `publicpa...@gmail.com` on 28 May 2013 at 7:04

**Comment by bleskodev** [comment]
Duplicate #603. Fixed.
