### ISSUE TITLE
RubyRipper crashes when encoding to MP3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bleskodev/rubyripper#588]
```
1) Please describe the steps to reproduce the situation:
a.Launch RubyRipper (rrip_gui or rrip_cli).
b.Check "MP3" under Codecs in Preferences.
c.Attempt to rip a CD

2) What is the expected output? What do you see instead?
I expect all selected tracks on the CD to be ripped and converted to MP3. 
Instead, RR trial rips the first selected track twice, generates an MD5 sum, 
then crashes with the following error:

/usr/lib64/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require': 
cannot load such file -- iconv (LoadError)
    from /usr/lib64/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /usr/lib64/ruby/site_ruby/2.0.0/rr_lib.rb:2464:in `mp3'
    from /usr/lib64/ruby/site_ruby/2.0.0/rr_lib.rb:2336:in `doMp3'
    from /usr/lib64/ruby/site_ruby/2.0.0/rr_lib.rb:2233:in `encodeTrack'
    from /usr/lib64/ruby/site_ruby/2.0.0/rr_lib.rb:2195:in `block (2 levels) in startEncoding'

3) What version of rubyripper are you using? On what operating system? The
gtk2 of commandline interface?

Version 0.6.2 on Linux (OpenSuse 13.1 Gnome), using either gtk or cli interface.

4) Is this not already fixed with the latest & greatest code? See for
instructions the Source tab above.

Unknown

5) Does the problem happen with all discs? If not, please attach
the output of cdparanoia -Q with a disc that gives trouble.

This problem happens with all discs I've tried.

6) Please explain why this change is important for you. Also, how many
users would benefit from this change?

This change is important for being able to add music to my MP3 collection. As 
it is now, I have to rip to flac (which does work), then use a separate 
converter to convert the flacs to MP3s.

Please provide any additional information below. The more usefull
information provided, the sooner the issue will be fixed.

Note that ruby versions older than 1.9 are no longer supported. You are
advised to upgrade instead.

```

Original issue reported on code.google.com by `briand...@gmail.com` on 1 Dec 2013 at 5:33

**Comment by clickwir** [comment]
On Ubuntu 17.04, I needed to install 'ruby-dev' and then I could run 'gem install iconv'. Otherwise gem would fail to install it. 

Now MP3's work fine.

**Comment by bleskodev** [comment]
Hi, can you check which version you are using?
The latest version (0.7.0rc1) from the github should not depend on iconv.
Thanks.

**Comment by clickwir** [comment]
Sorry, that would be very useful information to supply. 

I am still using the last release from the original dev. I think 0.6.5 or close to that. NOT using any version from git.
