### ISSUE TITLE
musicbrainz: undefined method `length' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by Safari77** [bleskodev/rubyripper#602]
ruby-2.3.3-61.fc24

```
DEBUG: CGI query: http://musicbrainz.org/ws/2/discid/PgdWkRrXwK0mEarbIaP4efZaElo-?toc=1+15+348427+150+23482+61650+89185+92095+119412+127900+148425+152640+176960+187247+231925+238402+268370+286377&inc=artists+recordings+artist-credits+release-groups
/x/rubyripper/lib/rubyripper/metadata/musicbrainz/getMusicBrainzRelease.rb:143:in `block in multipleReleasesFound': undefined method `length' for nil:NilClass (NoMethodError)
	from /x/rubyripper/lib/rubyripper/metadata/musicbrainz/getMusicBrainzRelease.rb:138:in `each'
	from /x/rubyripper/lib/rubyripper/metadata/musicbrainz/getMusicBrainzRelease.rb:138:in `multipleReleasesFound'
	from /x/rubyripper/lib/rubyripper/metadata/musicbrainz/getMusicBrainzRelease.rb:113:in `analyzeQueryResult'
	from /x/rubyripper/lib/rubyripper/metadata/musicbrainz/getMusicBrainzRelease.rb:45:in `queryDisc'
	from /x/rubyripper/lib/rubyripper/metadata/musicbrainz.rb:41:in `get'
	from /x/rubyripper/lib/rubyripper/metadata/main.rb:63:in `musicbrainz'
	from /x/rubyripper/lib/rubyripper/metadata/main.rb:54:in `startup'
	from /x/rubyripper/lib/rubyripper/metadata/main.rb:36:in `block in get'
	from /x/rubyripper/lib/rubyripper/metadata/main.rb:35:in `each'
	from /x/rubyripper/lib/rubyripper/metadata/main.rb:35:in `get'
	from /x/rubyripper/lib/rubyripper/disc/disc.rb:106:in `setMetadata'
	from /x/rubyripper/lib/rubyripper/disc/disc.rb:40:in `scan'
	from /x/rubyripper/lib/rubyripper/gtk2/gtkDisc.rb:44:in `refresh'
	from /x/rubyripper/lib/rubyripper/gtk2/gtkDisc.rb:37:in `start'
	from ./rubyripper_gtk2:146:in `block in scanDisc'
```

**Comment by bleskodev** [comment]
Thanks for reporting the bug. It should be fixed.
It would be nice if you can confirm the fix so that the bug can be closed.

**Comment by bleskodev** [comment]
In the absence of the feedback, I'm supposing the bug has been fixed and. Closing.
