### ISSUE TITLE
main.rb:184:in `add': undefined method `empty?' for 1:Fixnum (NoMethodError)

### ISSUE THREAD

**Issue by Safari77** [bleskodev/rubyripper#605]
Hmm, it ripped one track ok and then crashed

```
/wrk/safari/cvs/rubyripper-fork/lib/rubyripper/codecs/main.rb:184:in `add': undefined method `empty?' for 1:Fixnum (NoMethodError)
	from /wrk/safari/cvs/rubyripper-fork/lib/rubyripper/codecs/main.rb:125:in `block in addTags'
	from /wrk/safari/cvs/rubyripper-fork/lib/rubyripper/codecs/main.rb:117:in `each'
	from /wrk/safari/cvs/rubyripper-fork/lib/rubyripper/codecs/main.rb:117:in `addTags'
	from /wrk/safari/cvs/rubyripper-fork/lib/rubyripper/codecs/main.rb:70:in `block in command'
	from /wrk/safari/cvs/rubyripper-fork/lib/rubyripper/codecs/main.rb:66:in `each'
	from /wrk/safari/cvs/rubyripper-fork/lib/rubyripper/codecs/main.rb:66:in `command'
	from /wrk/safari/cvs/rubyripper-fork/lib/rubyripper/encode.rb:137:in `encodeTrack'
	from /wrk/safari/cvs/rubyripper-fork/lib/rubyripper/encode.rb:81:in `block in startEncoding'
	from /wrk/safari/cvs/rubyripper-fork/lib/rubyripper/encode.rb:79:in `each'
	from /wrk/safari/cvs/rubyripper-fork/lib/rubyripper/encode.rb:79:in `startEncoding'
	from /wrk/safari/cvs/rubyripper-fork/lib/rubyripper/encode.rb:70:in `addTrack'
	from /wrk/safari/cvs/rubyripper-fork/lib/rubyripper/secureRip.rb:99:in `ripTrack'
	from /wrk/safari/cvs/rubyripper-fork/lib/rubyripper/secureRip.rb:74:in `block in ripTracks'
	from /wrk/safari/cvs/rubyripper-fork/lib/rubyripper/secureRip.rb:70:in `each'
	from /wrk/safari/cvs/rubyripper-fork/lib/rubyripper/secureRip.rb:70:in `ripTracks'
	from /wrk/safari/cvs/rubyripper-fork/lib/rubyripper/secureRip.rb:59:in `startTheRip'
	from /wrk/safari/cvs/rubyripper-fork/lib/rubyripper/rubyripper.rb:63:in `startRip'
	from ./rubyripper_gtk2:387:in `block in updateInterfaceAndStartRip'
```

**Comment by bleskodev** [comment]
Thanks for reporting. It should be fixed now. Can you confirm? Thanks.

**Comment by bleskodev** [comment]
Considering the bug fixed. Closing the issue.
